### PR TITLE
Add unit & conversion for pixels

### PR DESCRIPTION
**Pull request by tr1sm0s1n**
- Included Pixels (unit & conversion).
- Useful for creating pdf from images.

### CODE REVIEW

**Comment by oneplus1000** [comment]
I'm confused about pixel units because as far as I know, pdf uses "Point" (1 point = 1/72 inch) to measure everything. So I don't understand how it can be converted to pixels. Could you please explain this to me?

**Comment by tr1sm0s1n** [comment]
In some of our projects, we want to generate PDFs from images. So, at the moment, we do it like this:
```go
file, err := os.Open(template.BaseImage)
if err != nil {
	return nil, err
}

defer file.Close()
// converting file to image format
base, _, err := image.Decode(file)
if err != nil {
	return nil, err
}

// to convert pixels to points
const conv float64 = 0.75

//Getting size of the image
bounds := base.Bounds()

// initializing size for the pdf
pdf := gopdf.GoPdf{}
size := gopdf.Rect{W: float64(bounds.Dx()) * conv, H: float64(bounds.Dy()) * conv}

// initializing pdf with the same size as the image
pdf.Start(gopdf.Config{PageSize: size, Unit: gopdf.UnitPT})
pdf.AddPage()
//Adding image as the background
if err = pdf.ImageFrom(base, 0, 0, &size); err != nil {
	return nil, err
}
```

Since `base.Bounds()` returns image resolution in Pixels, we had to convert the image resolution to Points.
Hence, having UnitPX in the config would be nice.

P.S. If you have a better workaround, we would welcome it.

**Comment by oneplus1000** [comment]
```
// to convert pixels to points
const conv float64 = 0.75 
```
Is it correct that this value of 0.75 comes from estimating that the image has a DPI of 96 DPI? (72/96 = 0.75 ). The point is, shouldn't we hard code this value in the lib or not? Because we can't be sure. That everyone who comes to use the lib uses images at 96 DPI. If I misunderstood something, please correct me. 
And I'm sorry if I said anything wrong. I'm not good at English.

**Comment by tr1sm0s1n** [comment]
Nothing at all. Your concerns are valid; what you have said is true.
Here, we assume the same conversion for all images, even those with higher DPI. Unfortunately, the `image` package doesn't provide any utility to get the DPI of the given image.

If we provide a dynamic conversion between pixels and points, the result PDF would be much larger in size and resolution.

**Comment by tr1sm0s1n** [comment]
@oneplus1000 Any thoughts?

**Comment by oneplus1000** [comment]
I think maybe we should use 3/4 (96dpi) as the default. and some mechanism for users to easily change this value. Please give me some time to think. I probably have free time again over the weekend.

**Comment by oneplus1000** [comment]
https://github.com/oneplus1000/gopdf/tree/config_convert_unit

I tried modifying it from your code. I added Config.ConversionForUnit so that the user can change the value of the conversionUnit themselves.


example
```go
//If the user wants to use 0.75 ( = 72 / 96 ) which is the default value.
pdf.Start(gopdf.Config{PageSize: size , Unit: gopdf.UnitPX}) 
```
```go
//Or in case the user wants to define it himself (This code will work like the code above.)
pdf.Start(gopdf.Config{PageSize: size , ConversionForUnit : 0.75 }) 
```
```go
//So if the user wants to use another value such as 300 dpi.
pdf.Start(gopdf.Config{PageSize: size ,  ConversionForUnit :  72.0 / 300.0 })  
```
In summary, 0.75 is the default value, but the user can still change it by set value in ConversionForUnit.

So I want to know your opinion.

**Comment by tr1sm0s1n** [comment]
Looks good. This meets most conditions.
Great work. 👏

**Pull request merged**
